### ISSUE TITLE
swap the stream contexts with the taskgroup context

### ISSUE THREAD

**Issue by graingert** [florimondmanca/aiometer#27]
```
        with send_channel, receive_channel:
            async with anyio.create_task_group() as task_group:
```

would be better as

```
        async with anyio.create_task_group() as task_group:
            with send_channel, receive_channel:
```

this way closing the amap context manager (None, None, None)ly would allow currently running tasks to finish, and prevent new tasks being added. Closing the amap context manager (type[T], T, tb)ly would still cancel all tasks

**Comment by florimondmanca** [comment]
@graingert Interesting. Would you happen to have a concrete use case to illustrate cases that this would address?

**Comment by graingert** [comment]
@florimondmanca looking for a soft-cancel approach for @pfmoore here https://github.com/agronholm/anyio/discussions/333#discussioncomment-960478

**Comment by florimondmanca** [comment]
So would a use case be something like "making the following work reliably"…?

```python
async with amap(process, items) as results:
    async for r in results:
        first_result = r
        break  # Should cleanly cancel tasks for other items on exitting `async with amap`.
```

**Comment by florimondmanca** [comment]
@graingert Applying your suggestion, I get a `ClosedResourceError` on the following example:

```python
import random

import aiometer
import trio


async def process(item: int) -> int:
    delay = random.random()
    await trio.sleep(delay)
    return item


@trio.run
async def main() -> None:
    items = list(range(10))

    async with aiometer.amap(process, items) as results:
        async for r in results:
            result = r
            break

    print(result)
```

```console
Traceback (most recent call last):
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/debug/example.py", line 14, in <module>
    async def main() -> None:
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/venv/lib/python3.9/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/debug/example.py", line 20, in main
    break
  File "/Users/florimond/.pyenv/versions/3.9.0/lib/python3.9/contextlib.py", line 182, in __aexit__
    await self.gen.__anext__()
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/src/aiometer/_impl/amap.py", line 88, in _amap
    yield receive_channel
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/venv/lib/python3.9/site-packages/anyio/_backends/_trio.py", line 139, in __aexit__
    return await self._nursery_manager.__aexit__(exc_type, exc_val, exc_tb)
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/venv/lib/python3.9/site-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/src/aiometer/_impl/amap.py", line 77, in sender
    await run_on_each(
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/src/aiometer/_impl/run_on_each.py", line 60, in run_on_each
    task_group.start_soon(_worker, async_fn, index, value, config)
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/venv/lib/python3.9/site-packages/anyio/_backends/_trio.py", line 139, in __aexit__
    return await self._nursery_manager.__aexit__(exc_type, exc_val, exc_tb)
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/venv/lib/python3.9/site-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/src/aiometer/_impl/run_on_each.py", line 24, in _worker
    await config.send_to.send(result)
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/venv/lib/python3.9/site-packages/anyio/streams/memory.py", line 191, in send
    self.send_nowait(item)
  File "/Users/florimond/Developer/florimondmanca-projects/aiometer/venv/lib/python3.9/site-packages/anyio/streams/memory.py", line 173, in send_nowait
    raise ClosedResourceError
anyio.ClosedResourceError
```

I believe this is because now `send_channel` and `receive_channel` are closed and _then_ `sender` tasks are handled, which gives time for a `sender` to try to `.send()` just before tasks are cancelled, causing a `ClosedResourceError`.

See, if I add some `prints()`'s in `_worker()` in `run_in_each.py`, just before the call to `.send()`:

```python
        print(f"sending {result}...")
        await config.send_to.send(result)
        print(f"sent {result}")
```

The chain of events is:

```console
sending 3...  # first_result
send 3
done  # broke out of loop, `aexit` runs
sending 7...  # Causes the exception below
[...] ClosedResourceError [...]
```

**Comment by graingert** [comment]
you would do

```python
async def worker(async_fn, fount, sink):
    with fount, sink:
        async for item in fount:
            result = await async_fn(item)
            try:
                await fount.send(item)
            except anyio.ClosedResourceError:
                break
```

this way closing the pipes cleanly stops the flow of work, but not the work itself

**Comment by graingert** [comment]
also anyio 3 supports taskgroup.start so you can limit tasks with:

```python
async def execute_task(semaphore, async_fn, \, *args, task_status, **kwargs):
    async with semaphore:
        task_status.started()
        await async_fn(*args, **kwargs)

async with anyio.create_task_group() as tg:
    for task in tasks:
        await tg.start(execute_task, task, semaphore)
```
